{% set name = "Ipopt" %}
{% set version = "3.12.7" %}
{% set sha256 = "9c8b02149fa4f0cdf63e838ae68f86aa41a577d7f05932139eede9179f314861" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.coin-or.org/download/pkgsource/{{ name }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - mumps_mpi.patch

build:
  skip: True  # [win]
  number: 1
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - ampl-mp
    - mumps
    - metis 5.1.*
    - scotch
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

  run:
    - ampl-mp
    - mumps
    - metis 5.1.*
    - scotch
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

test:
  files:
    - test
    - mytoy.nl

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL 1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization'

extra:
  recipe-maintainers:
    - pstjohn
